### ISSUE TITLE
Tooltip "risico" gaat aan in "hoog-risico-AI" (wat ander 'risico' is)

### ISSUE THREAD

**Issue by OXKuiperBZK** [MinBZK/Algoritmekader#181]
De tooltip voor het woord "risico" gaat ook aan in "hoog-risico-AI". Deze tooltip zou daar niet moeten werken. Het woord "risico" is iets anders dan "hoog-risico-AI", de laatste is een hele specifieke categori/label, de eerste is een breder concept.

Dit komt terug op allerlei plekken, maar meest opvallend in de tabel bij iedere vereiste.

![image](https://github.com/user-attachments/assets/1158cffe-6729-49ba-9d4a-6957af74a466)

(hiermee samenhangend: Ik stel voor dat "hoog-risico-AI" altijd vervangen wordt door "hoog-risico-AI-(EU)" om duidelijk te maken dat het de categorie uit de AI-verordening is.)

**Comment by ruthkoole** [comment]
Deze tabel is overal weggehaald in #261. Daardoor komt dit specifieke probleem niet meer voor. We hebben nu tooltips voor definities volgens Artikel 3 AI-verordening. Daar wordt hoog risico AI niet zo specifiek gedefinieerd. Ik zal nog kijken of we daar wel een definitie van toe willen voegen.

**Comment by ruthkoole** [comment]
Dit is al gefixt in #346
