### ISSUE TITLE
Blokje Instrumenten toevoegen aan elke vereiste-pagina?

### ISSUE THREAD

**Issue by noutvandeijck** [MinBZK/Algoritmekader#189]
Nu zijn de bijbehorende instrumenten alleen op vereisten-pagina's te zien die we tot nu al gekóppeld hebben aan een instrument. 

Maar in het vervolg willen (denk ik?) bij elke vereiste (en misschien zelfs bij elke maatregel) zien welke instrumenten er mogelijk gekoppeld zijn aan die vereiste.

Er valt ook wat te zeggen om het niet te doen, en alleen instrumenten genoemd te zien worden als een vereiste daadwerkelijk gekoppeld is aan een instrument, want anders blijft het onder dat kopje leeg. Echter gaan dan de vereiste pagina's soms wel, en soms niet, een kopje Instrumenten bevatten.

**Comment by ruthkoole** [comment]
Ik vraag me af of je dit overal wilt, of alleen daar waar het relevant is? Volgens mij doen we dit nu waar het relevant is? Is dat voldoende denk je om dit op te lossen @noutvandeijck ?

Dan zouden we dit issue kunnen afsluiten?
