### ISSUE TITLE
In vergelijking met de oude versie van deze pagina mis ik hier nu iets over:

### ISSUE THREAD

**Issue by ruthkoole** [MinBZK/Algoritmekader#220]
In vergelijking met de oude versie van deze pagina mis ik hier nu iets over:

- hoe is informatie in het algoritmekader met elkaar verbonden? Ik denk dat het wel goed is om uit te leggen dat je informatie kan benaderen via de levenscyclus, rollen of onderwerpen. Waarom is dat belangrijk? Misschien ook goed hier kort uit te leggen wat het verschil is tussen vereisten en maatregelen, etc. 
- Het stuk over standaarden moet ook ergens terugkomen. Daar zijn best veel vragen over (wat is de relatie tussen het kader en de standaarden?)
- vermelden dat het Algoritmekader een doorontwikkeling is van het implementatiekader. Dat is een officieel document (gedeeld met de kamer etc). 

Als we deze informatie nog ergens een plek kunnen geven, lijkt het me een hele mooie verbetering zo! Mooi werk!

_Originally posted by @ruthkoole in https://github.com/MinBZK/Algoritmekader/issues/193#issuecomment-2272799133_

**Comment by webredactie-algoritmekader** [comment]
Volgens mij is dit allemaal opgelost in versie 2.1!
