### ISSUE TITLE
Edit-link of algemene link naar Github?

### ISSUE THREAD

**Issue by webredactie-algoritmekader** [MinBZK/Algoritmekader#221]
Ik heb steeds de edit-link gebruikt die op elke pagina staat onder het icoontje rechtsboven.

_Originally posted by @webredactie-algoritmekader in https://github.com/MinBZK/Algoritmekader/pull/197#discussion_r1711851342_

**Comment by ruthkoole** [comment]
Edit link lijkt me prima!
