### ISSUE TITLE
Systeemeigenaar is een nieuwe rol

### ISSUE THREAD

**Issue by noutvandeijck** [MinBZK/Algoritmekader#223]
"Systeemeigenaar is een nieuw rol. Wel belangrijk!"

Systeemeigenaar en productowner worden genoemd in de maatregel 'richt_formeel_wijzigingenproces_in'.
Moeten wellicht nieuwe rollen worden in het Algoritmekader.

_Originally posted by @BartdeVisser in https://github.com/MinBZK/Algoritmekader/pull/211#discussion_r1714935345_

**Comment by ruthkoole** [comment]
Niet meer relevant door nieuwe indeling rollen #311
