### ISSUE TITLE
Checken voorbeeld biasanalyse

### ISSUE THREAD

**Issue by ruthkoole** [MinBZK/Algoritmekader#228]
we zijn met deze maatregel nog bezig, die staat er nu nog niet in. Tzt kijken of dit nog overeenkomt? Of hier een ander voorbeeld nemen die nu al inhet kader staat?

_Originally posted by @ruthkoole in https://github.com/MinBZK/Algoritmekader/pull/197#discussion_r1706761831_

**Comment by noutvandeijck** [comment]
Dit is opgelost omdat algemene tekst bias volledig is herzien!
