### ISSUE TITLE
Meer info nodig voor redactieslag Governance

### ISSUE THREAD

**Issue by webredactie-algoritmekader** [MinBZK/Algoritmekader#233]
Hier mist wat mij betreft nu wel een uitleg over wat we bedoelen met governance. Er is best veel discussie geweest over wat het is (het is zo'n breed begrip met meerdere interpretaties). Volgens mij moeten we dat wel goed uitleggen. Ik vind het nu iets te kort. Een expert die zich veel bezighoudt met dit onderwerp moet ook voldoende diepgang kunnen vinden

_Originally posted by @ruthkoole in https://github.com/MinBZK/Algoritmekader/pull/194#discussion_r1706563464_

**Comment by ruthkoole** [comment]
Niet meer relevant door de nieuwe teksten van governance
