### ISSUE TITLE
Bullet toevoegen op pagina met vereisten

### ISSUE THREAD

**Issue by FrieseWoudloper** [MinBZK/Algoritmekader#257]
Op de pagina over vereisten staat:

> Welke vereisten gelden voor jouw organisatie, hangt af van:
> 
> de technologie die je gebruikt: rekenregels, machinelearning of generatieve AI
> de risicoclassificatie van het algoritme dat je gebruikt

Als het om een HRAI systeem gaat, is een derde punt of je 'slechts' deployer of (ook) provider bent. Ik denk dat het belangrijk is om dat expliciet te noemen, omdat de leiding van overheidsorganisaties hier over na moet denken en een besluit over moet nemen:
Willen we zelf HRAI-systemen ontwikkelen en zijn we dan ook in staat om te voldoen aan de vereisten voor providers uit de AI-Act, of kiezen we ervoor om geen HRAI te gebruiken of HRAI altijd in te kopen (zodat de vereisten beperkt blijven tot die voor deployers)? Het lijkt me dé vraag die veel overheidsorganisaties op dit moment moeten beantwoorden, die ook verstrekkende gevolgen kan hebben voor AI en datateams, de projectenportfolio, het aannemen van nieuwe mensen, inkoop, enz.

**Comment by ruthkoole** [comment]
Dank voor de suggestie. Belangrijke toevoeging inderdaad. Een bullet toegevoegd in #262
