### ISSUE TITLE
Issues op aparte pagina? 

### ISSUE THREAD

**Issue by Jellie2022** [MinBZK/Algoritmekader#27]
De link waarin we vragen om een bijdrage, verwijst naar een pagina waar mensen een heel stuk moeten zoeken, om te weten hoe ze een issue kunnen melden. 

Kunnen we de issues op de repo niet op een aparte pagina zetten, zodat we daar direct heen kunnen linken? Of zelfs direct linken naar 'issues aanmaken'.  Want het aanmaken van een issue zelf, is helemaal niet lastig. (Want dat ging ik ook even proberen).

**Comment by ruthkoole** [comment]
Hoi @Jellie2022 ! Dank voor het aanmaken van het issue. 

Even kijken of ik je goed begrijp.. Bedoel je om op https://minbzk.github.io/Algoritmekader/ de tekst onder **Bijdragen?** de tekst aan te vullen en direct te linken naar de issue pagina waar je een issue kan aanmaken?

**Comment by Jellie2022** [comment]
Hoi Ruth,

Jij bent snel!

Ik ben idd nu bezig met een review van https://minbzk.github.io/Algoritmekader/.

Daar staat in de disclaimer een link naar issues. Ik denk dat je beter direct naar de issues kunt linken, dan naar de repo pagina.

Ik heb nu dit voorgesteld in het tekstbestand (Dat deel ik later helemaal met je, dus wacht maar even met de actie):

Een voorproefje:

Proclaimer
Het Algoritmekader is volop in ontwikkeling. Dan doen we open en transparant. Je kunt mee-ontwikkelen en zelf je bijdragen leveren. [dit moet linken naar een pagina waar het duidelijk is hoe je een bijdrage levert, maar dan niet alleen via Github, ook moeten daar de sprintreviews instaan en de andere manieren om mee te praten, denken bij te dragen]. Heb je een opmerking over het beter kan, of zie je iets wat niet klopt, laat het weten. Maak daarvoor een issue aan<https://github.com/MinBZK/Algoritmekader/issues> (kies ‘new issue’ op de groene knop rechtsboven). Lukt dat niet, mail ons dan via ***@***.******@***.***>.

Hoe je kunt  bijdragen op Github vind ik nu nog echt heel erg lastig beschreven, dus daar moeten we nog echt even goed naar kijken. Om te voorkomen dat we mensen buitensluiten.

Op 30 jan 2024, om 16:28 heeft Ruth Koole ***@***.***> het volgende geschreven:



Hoi @Jellie2022<https://github.com/Jellie2022> ! Dank voor het aanmaken van het issue.

Even kijken of ik je goed begrijp.. Bedoel je om op https://minbzk.github.io/Algoritmekader/ de tekst onder Bijdragen? de tekst aan te vullen en direct te linken naar de issue pagina waar je een issue kan aanmaken?

**Comment by ruthkoole** [comment]
@Jellie2022 kunnen we dit issue sluiten gezien de recente aanpassingen?

**Comment by Jellie2022** [comment]
Ja, heb ik gedaan. (Wist niet dat dat moest).


Op 14 feb 2024, om 19:07 heeft Ruth Koole ***@***.***> het volgende geschreven:



@Jellie2022<https://github.com/Jellie2022> kunnen we dit issue sluiten gezien de recente aanpassingen?
