### ISSUE TITLE
Links naar andere levenscyclus pagina's ontbreekt

### ISSUE THREAD

**Issue by jaap-vink** [MinBZK/Algoritmekader#300]
**Beschrijf de fout**
Bij de pagina's van de levenscyclus, behalve bij "Organisatie verantwoordelijkheden" ontbreken de links naar de andere fases.

**Screenshots**
Voeg eventueel een screenshot toe. 

![image](https://github.com/user-attachments/assets/5c30c0b0-0c54-45da-8d48-609a2e393d4f)
![image](https://github.com/user-attachments/assets/b51ff146-f87a-4290-a43d-c719c0ee3fe2)
![image](https://github.com/user-attachments/assets/b1dcf6ba-88ca-4c8b-92fc-7f7eab6c8de1)

**Comment by ruthkoole** [comment]
Goed opgemerkt Jaap! Ik heb het opgeslost in #303
