### ISSUE TITLE
Gevallen op verzoek verwijderen

### ISSUE THREAD

**Issue by jaspervanderheide** [MinBZK/Algoritmekader#309]
## Beschrijf je suggestie
docs/vereisten/aia-20-verstrekken-van-informatie-op-verzoek.md laten vervallen

## Leg uit waarom dit een goede toevoeging is aan het Algoritmekader

Dit is alleen op verzoek. Het is dus niet een eis waar vooraf aan voldaan moet worden. We gaan ook niet voor andere wetten (hopelijk) opschrijven wat de bevoegdheden van toezichthouders zijn. Ik neem aan dat de gevraagde documentatie al vereist is onder andere vereiste. Anders de vereisten veranderen zodat de documentatie centraal staat, niet het verzoek.

**Comment by floort** [comment]
Onderschat niet hoeveel voorbereiding er nodig is om documentatie aan te kunnen leveren om compliance aan te tonen. Dit is vergelijkbaar met artikel 5 van de AVG. Het verschil tussen moeten voldoen aan de wet en aantoonbaar moeten voldoen is ook in de gevallen waarbij nooit gevraagd wordt om het daadwerkelijk aan te tonen enorm. Als er geen voorbereiding nodig zou zijn zou artikel 21 van de verordening kunnen volstaan met de mededeling dat toezichthouders beschikbare documenten  en informatie kunnen opvragen.

**Comment by jaspervanderheide** [comment]
Ik ben het daar mee eens. Maar voor een organisatie wil ik dan liever duidelijk maken dat ze goed moeten documenteren (met de opmerking dat het opgevraagd kan worden), dan het op de huidige manier te verwoorden. Liever één keer duidelijk, dan twee keer op deze manier overlappend. De technische documentatie wordt al als vereiste gesteld in artikel 11 (of [nummer 6 in algoritmekader](https://minbzk.github.io/Algoritmekader/vereisten/aia-06-technische-documentatie/index.html)). Volgens mij volstaat het dan om in die vereiste te verwijzen naar de bevoegdheid van autoriteiten uit artikel 21, in plaats van twee losse vereisten. Of zie jij dan nog verschillen tussen de eisen?
