### ISSUE TITLE
Label governance geeft 404

### ISSUE THREAD

**Issue by OXKuiperBZK** [MinBZK/Algoritmekader#324]
Het [label governance](https://minbzk.github.io/Algoritmekader/onderwerpen/governance) leidt tot 404 (zie label hieronder voor duidelijkheid). Ik denk omdat het een onderwerp is, “[onderwerpen](https://minbzk.github.io/Algoritmekader/onderwerpen/)”, maar ook een kopje (Algoritmekader/governance/)

![image](https://github.com/user-attachments/assets/199cfebf-bd25-4d8f-8449-93fa80a21066)

**Comment by OXKuiperBZK** [comment]
Ruth: Komt gaandeweg goed. Geen urgentie,

**Comment by ruthkoole** [comment]
Dit gaat met de omvorming naar de nieuwe huisstijl goed
