### ISSUE TITLE
Nummering levenscyclus sluit niet aan

### ISSUE THREAD

**Issue by jaap-vink** [MinBZK/Algoritmekader#326]
**Beschrijf de fout**
Op https://minbzk.github.io/Algoritmekader/levenscyclus/ staat de nummering verkeerd. Organisatieverantwoordelijkheden is fase 0 niet 1. Daardoor sluit de text niet aan bij de flowchart.

**Screenshots**
Voeg eventueel een screenshot toe. 

![Screenshot 2024-10-15 090927](https://github.com/user-attachments/assets/71c7c869-f510-4248-86ea-ffdb33031569)

**Comment by ruthkoole** [comment]
Dank Jaap! Ik heb het opgelost in #327.
