### ISSUE TITLE
Levenscyclus, plaatje telt vanaf 0, lijstje vanaf 1

### ISSUE THREAD

**Issue by OXKuiperBZK** [MinBZK/Algoritmekader#329]
Plaatje gaat vanaf 0, de lijst vanaf 1. https://minbzk.github.io/Algoritmekader/levenscyclus/

start=0 oplossing lijkt niet te werken om de lijst vanaf 0 te laten starten.

**Comment by ruthkoole** [comment]
is al opgelost in #327
