### ISSUE TITLE
De categorie "hoog-risico" moet niet de hover-over risico tooltip tonen

### ISSUE THREAD

**Issue by OXKuiperBZK** [MinBZK/Algoritmekader#333]
De risico krijg je de hover-over-info: "de combinatie van kans op schade en de ernst van die schade", maar dat is daar onjuist. De categorie high-risk kijkt _niet_ naar kans/frequentie. Het is volledig op toepassing/domein/onderwerp. Dit maakt het verwarrend wat "hoog-risico" is (een categorie, niet een traditionele risico-inschatting op basis van een risicoanalyse.)

Dit is ook bijv wat in de annotated AI-act wordt genoemd als verwarrend iets aan de AI-act.

![image](https://github.com/user-attachments/assets/989e0958-f640-4701-a484-292d6a294c35)

**Comment by ruthkoole** [comment]
dubbel met #181
