### ISSUE TITLE
Risicobeheer, Kwaliteitsbeheer, AI geletterdheid, en andere "Governance"vereisten  ook bij levenscyclus 0 "Organisatieverantwoordelijkheden" 

### ISSUE THREAD

**Issue by jaap-vink** [MinBZK/Algoritmekader#339]
## Beschrijf je suggestie
De vereisten voor Risicobeheer & kwaliteitsbeheer, AI-geletterdheid en anderen  horen ook bij levenscyclus 0 "Organisatieverantwoordelijkheden" . Ik denk dat die daar apart moeten worden genoemd maar misschien ook een directe link tussen levenscyclus 0 en governance (en v.v.)? 
Suggesties voor vereisten die bij levenscyclus 0 zouden kunnen komen:
aia-01
aia-03
aia-11
aia-20
aia-22
aia-23
aia-27

## Leg uit waarom dit een goede toevoeging is aan het Algoritmekader
Wanneer iemand insteekt vanuit de levenscyclus i.p.v. onderwerp (of v.v.) dan kunnen zij op deze manier een volledig beeld krijgen.

**Comment by ruthkoole** [comment]
Hi @jaap-vink

Dank voor je suggestie. We hebben wat opgeschoond afgelopen weken (zowel in tagging, als in maatregelen en vereisten).

De vereisten (uit de AI-verordening) die nu aan fase 0 hangen zijn:
- aia-01
- aia-03
- aia-11
- aia-18
- aia-22
- aia-23
- aia-28
- aia-35
- aia-37
- aia-38
- aia-39

Daarmee hangen er twee vereisten die jij noemt niet aan fase 0, te weten:
- aia-20: Deze is komen te vervallen in #312, omdat dit geen vereiste is waar overheden gelijk iets mee moeten. We hebben dit opgenoen in maatregel aia-06. 

- aia-27: deze hangt aan implementatie en monitoring en beheer. Gedachte is dat je gaat registreren wanneer je het in gebruik neemt, of al in gebruik hebt. 

Kan je je hierin vinden?

**Comment by ruthkoole** [comment]
Door het samenvoegen van vereisten, moet de nummering ook weer aangepast worden.

**Comment by jaap-vink** [comment]
Hallo Ruth,
Voor het grootste gedeelte. Alleen zal registratie eerder moeten plaatsvinden. Voor in gebruik name. (Behalve systemen die al voor 2/8/26 in gebruik zijn)
"**Alvorens** een in de in een bijlage bij deze verordening opgenomen gebruiksgevallen met een hoog risico vermeld AI-systeem te gebruiken, moeten gebruiksverantwoordelijken van AI-systemen met een hoog risico die overheidsinstanties, -agentschappen of -organen zijn, zich bij een dergelijke databank registreren en het systeem selecteren dat zij voornemens zijn te gebruiken." (tekstblok 131)
Artikel 49 lid 3: "**Alvorens** een in bijlage III vermeld AI-systeem met een hoog risico in gebruik te stellen of te gebruiken, met uitzondering van de in punt 2 van bijlage III vermelde AI-systemen met een hoog risico, registreren gebruiksverantwoordelijken die overheidsinstanties, instellingen, organen of instanties van de Unie, of personen die namens hen optreden, zichzelf en selecteren zij het systeem en registreren zij het gebruik ervan in de in artikel 71 bedoelde EU-databank."

Let op uitzondering registratie voor kritieke infrastructuur:  art. 49 5.   "AI-systemen met een hoog risico als bedoeld in punt 2 van bijlage III worden op nationaal niveau geregistreerd."
