### ISSUE TITLE
Toevoegen vereisten voor testen

### ISSUE THREAD

**Issue by jaap-vink** [MinBZK/Algoritmekader#340]
## Beschrijf je suggestie
Ik mis nog diverse vereisten voor het opzetten en uitvoeren van een test strategie. Ik zie alleen verwijzingen naar verwerking van persoonsgegevens in AI-testomgeving voor regelgeving.
Zowel de risicobeheer vereisten als de kwaliteitsbeheer artikelen bevatten vereisten voor testen (en documentatie daarvan)

Zie bijvoorbeeld:

Artikel 9

6.AI-systemen met een hoog risico worden getest met het oog op het vaststellen van de passendste en gerichte risicobeheersmaatregelen. De tests zorgen ervoor dat AI-systemen met een hoog risico consistent presteren ten aanzien van het beoogde doel ervan en in overeenstemming zijn met de eisen van deze afdeling.

8.Het testen van AI-systemen met een hoog risico vindt, zoals passend, in de loop van het ontwikkelingsproces plaats en in ieder geval voordat het systeem in de handel wordt gebracht of in gebruik wordt gesteld. Er wordt getest aan de hand van vooraf vastgestelde beoordelingsmaatstaven en probabilistische drempels die passend zijn voor het beoogde doel van het AI-systeem met een hoog risico.

Artikel 17
1 d)
procedures voor het inspecteren, testen en valideren die vóór, tijdens en na de ontwikkeling van het AI-systeem met een hoog risico moeten worden uitgevoerd en de regelmaat waarmee zij moeten worden uitgevoerd;

Artikel 59
1 i)
een volledige en gedetailleerde beschrijving van het proces en de onderbouwing van het trainen, testen en valideren van het AI-systeem wordt samen met de testresultaten bewaard als onderdeel van de in bijlage IV bedoelde technische documentatie;
## Leg uit waarom dit een goede toevoeging is aan het Algoritmekader
Testen is vaak een "vergeten" onderwerp wanneer algoritmes in systemen worden ingezet. Het belang expliciet maken kan problemen bij gebruik in de praktijk voorkomen.

**Comment by jaap-vink** [comment]
En er zou ook aandacht moten zijn voor Artikel 60 "Testen van AI-systemen met een hoog risico onder reële omstandigheden buiten AI-testomgevingen voor regelgeving". Met de daarin opgenomen vereisten.

**Comment by BartdeVisser** [comment]
Hi Jaap,

Dank en duidelijk verhaal. Ik ga ermee aan de slag, zodat dit nog in deze release meegaat.

Groet,
Bart

**Comment by BartdeVisser** [comment]
Hi Jaap,

Ik heb geprobeerd om e.e.a. te verwerken: https://github.com/MinBZK/Algoritmekader/blob/main/docs/voldoen-aan-wetten-en-regels/vereisten/aia-39-testen.md. Dit gaat komende release mee. Op sommige punten wellicht nog wat kort in de bocht vanwege deadline die nadert, maar laten het reviewproces van open werken zijn werk doen. 

Dank nogmaals voor je scherpe kijk erop!

Groet,
Bart

**Comment by jaap-vink** [comment]
Hallo Bart,

Ziet er als 1ste versie goed uit. Mee eens, verder uitwerken moet organisch gebeuren. Misschien dat we wat test specialisten kunnen activeren :-)

Groet,

Jaap
