### ISSUE TITLE
Publieke Inkoop: Aandacht voor aankoop producten in Bijlage 1?

### ISSUE THREAD

**Issue by jaap-vink** [MinBZK/Algoritmekader#350]
## Beschrijf je vraag
Wordt er ook aandacht besteed in het onderwerp "Publieke Inkoop" aan de rol als 'gebruiksverantwoordelijke', wanneer overheden producten aanschaffen die onder bijlage 1 vallen?

**Comment by BartdeVisser** [comment]
Hi Jaap, 

Dank voor je vraag! Bedoel je bijlage 1 of toevallig 3 van de AI-Verordening? Met het deel publieke inkoop proberen we met een aantal maatregelen inzicht te geven in wat er moet gebeuren. Via de logica van de Beslisboom koppelen we (voor zover ik weet) zowel de rol van aanbieder als gebruiksverantwoordelijke aan de vereisten waar deze mee aan de slag moet gaan. Antwoord op je vraag of heb je een voorstel om zaken te verduidelijken?

**Comment by jaap-vink** [comment]
Hallo Bart,

Nee, ik bedoel Bijlage 1 (de systemen die vallen onder Artikel 6, lid 1). Als een overheid bijvoorbeeld een liftb of een bosbouwvoertuig aanschaft waarin een AI gestuurde veiligheidscomponent in zit dan is dat een Hoog Risico AI-systeem en is die overheid de gebruiksverantwoordelijke. Tenzij ik het verkeerd begrijp :-) Ik vermoed dat die overheid daar ook in het inkoopproces aandacht aan moet besteden?

Groet,

Jaap

**Comment by BartdeVisser** [comment]
Hi Jaap,

Ja goed punt. Als duidelijk is in welke risico categorie een toepassing valt, moet uiteraard worden bekeken welke vereisten hierop van toepassing zijn. Aanvullend uiteraard welke verantwoordelijkheden er dan zijn voor de gebruiksverantwoordelijke. 

In de maatregelen laag die een tag hebben op 'publieke inkoop' wordt de beslishulp genoemd. Wij denken dat deze beslishulp bij uitstek nuttig is om in te zetten bij de fase 'behoeftestelling' in het inkoopproces. Juist daar moet een multidisciplinair (inkoop)team afwegingen gaan maken waar ze mee te maken hebben en wat de gevolgen zijn als bepaalde voorzieningen worden ingekocht. Dus ook de realisatie dat het om veiligheidscomponenten gaat, moet er uiteraard wel zijn.

Met de doorontwikkeling van de beslishulp en de integratie met het Algoritmekader, verwacht ik dat deze inzichten dus ook onderdeel worden binnen het inkoopproces.

Suggestie om het nog op een andere manier onder de aandacht te brengen?

Groet,
Bart

**Comment by jaap-vink** [comment]
Hallo Bart,

Ik denk dat het in ieder geval goed is een opmerking op de "Onderwep"-pagina te plaatsen dat deze inhoud van toepassing is op inkoop van AI-systemen die zowel onder Bijlage 3 als onder Bijlage 1 vallen.
Groet,

Jaap
