### ISSUE TITLE
Proportionaliteit

### ISSUE THREAD

**Issue by jaspervanderheide** [MinBZK/Algoritmekader#40]
Is proportionaliteit niet ook een norm? Dit is iets wat veel terugkomt - direct of indirect - in IAMA en handreiking non discriminatie by design, maar ik zag deze nog niet terug bij de normen.

**Comment by floort** [comment]
Ik zou, net als ik bij het algoritmeregister heb voorgesteld, proportionaliteit, subsidiariteit en noodzaak alle drie benoemen. Ze hebben een ander soort onderbouwing nodig en hebben in de praktijk baat bij wat structuur omdat ze zelden redelijk onderbouwd worden.

https://github.com/MinBZK/Algoritmeregister/pull/9

**Comment by floort** [comment]
Ter info: ik heb bovenstaande pull request voor het register een update gegeven omdat het nooit is beoordeeld en ondertussen ruimschoots achter liep op de meest recente versie van het schema dat nu beschikbaar is.

**Comment by ruthkoole** [comment]
Dit zit nu in de vereiste https://minbzk.github.io/Algoritmekader/vereisten/beginsel_van_proportionaliteit_en_subsidiariteit/. Daarnaast krijgt het ook een plek in https://github.com/MinBZK/Algoritmekader/pull/250

Is dat voldoende wat jou betreft? Of moeten we nog iets aparts toevoegen?
