### ISSUE TITLE
AI Gids toevoegen aan maatregelen

### ISSUE THREAD

**Issue by ruthkoole** [MinBZK/Algoritmekader#411]
## Beschrijf je suggestie
De AI Gids van EZ is een mooi hulpmiddel: https://open.overheid.nl/documenten/8d7b5ccb-41fc-4d92-a4c2-a7fa81e66bfb/file

Deze kunnen we toevoegen als instrument

**Comment by noutvandeijck** [comment]
@ruthkoole denk je dat we deze nog als los hulpmiddel moeten toevoegen, als we hem ook al noemen in de uitleg over de AI verordening (zie https://github.com/MinBZK/Algoritmekader/pull/451)

Ben even kwijt of we hier nu vanochtend iets over afgesproken hadden.

**Comment by noutvandeijck** [comment]
Toevoegen aan maatregel Risicoclassificatie en andere belangrijke maatregelen.
