### ISSUE TITLE
Status/uitleg algoritmekader

### ISSUE THREAD

**Issue by Mildoooo** [MinBZK/Algoritmekader#417]
## Als ik de website open zie ik geen toelichting op het AK of een instructie hoe je het AK kan gebruiken.  
Het doel van het algoritmekader is om wet- en regelgeving in relatie tot de inzet en het gebruik van AI/algoritmes inzichtelijk en daardoor beter toepasbaar te maken. Hierdoor kunnen tijdig wetten en regels gevolgd worden waardoor de kans op nadelige impact voor burgers kleiner wordt. Naast wetten en regels, bevat het AK ook wettelijke of geadviseerde maatregelen. 

Het AK is een hulpmiddel om de inzet en het gebruik van AI/algoritmes te bezien in de context van wetten en regels. Wat het niet is: Het is geen toetsingskader, een compliancekader, of een beheerskader. Het AK bevat wel alle elementen die een rol spelen bij het toetsen van AI/algoritmes, of die bij het naleven van wetten en regels, of het beheersen van risico' s van belang zijn. Het AK is geen groene afvinklijst. 

Het AK kan overweldigend overkomen. Schrik niet. Het AK kan op verschillende manieren worden gebruikt. Het is niet nodig om alle onderwerpen te doorlopen, maar je kan het gebruiken als referentiedocument, voor het raadplegen van een specifiek onderwerp (b.v. bias/discriminatie). Of je wil een AI /algoritme dat al in gebruik is extra checken op 1 of meerdere onderwerpen. Het kan ook aanleiding zijn om voor je zelf een standaard werkwijze te ontwikkelen, b.v. t.a.v. beheersen van risico's.

**Comment by BartdeVisser** [comment]
@Mildoooo : In de website (footer) hebben we deze link opgenomen: https://minbzk.github.io/Algoritmekader/overhetalgoritmekader/#verantwoord-gebruik-van-algoritmes-en-ai. Heb jij dit kunnen vinden en zo ja, vond je het dan nog onvoldoende beschreven?
@webredactie-algoritmekader : Is er ruimte om e.e.a. nadrukkelijker naar voren te laten komen?

**Comment by webredactie-algoritmekader** [comment]
Wordt opgelost! Zie https://github.com/MinBZK/Algoritmekader/issues/439

(Ruben plaatst een CTA (call-to-action) op de homepage naar https://minbzk.github.io/Algoritmekader/overhetalgoritmekader/. In de volgende versie kijken of dit werkt/voldoende is.)
