### ISSUE TITLE
Definitie algoritme

### ISSUE THREAD

**Issue by Mildoooo** [MinBZK/Algoritmekader#418]
## Algoritme 
Mogelijk dat jullie de discussie al gehad hebben, maar de definitie van algoritme richt nu zich vooral op de techniek en niet op de inbedding van het algoritme in het primaire proces waar ook beleidsregels, menselijke beoordelingsruimte en werkinstructies deel van uitmaken. Juist daar kunnen dingen misgaan ('confirmation bias' ) of juist rechtgezet worden ('er wordt maatwerk geboden').

**Comment by BartdeVisser** [comment]
@Mildoooo : Klopt, we hanteren bij de definitie puur en alleen de definitie voor algoritmes. Hoe je aan de slag moet gaan met algoritmes, werken we uit in de maatregelen laag. Deze zaken die jij beschrijft zijn ofwel een onderwerp apart geworden, of inderdaad in een maatregel uitgewerkt. Het lijkt me ook moeilijk/wellicht niet helemaal zuiver om deze 'lading' te verwerken in een definitie.
