### ISSUE TITLE
Verantwoord datagebruik

### ISSUE THREAD

**Issue by IneVrenkenNationaalArchief** [MinBZK/Algoritmekader#428]
## Beschrijf je suggestie
Pagina: https://minbzk.github.io/Algoritmekader/onderwerpen/data/ 
Omschrijving.
Goed dat bij verantwoord datagebruik voor AI genoemd wordt dat verwerking van persoonsgegevens moet voldoen aan strenge kaders. Ik mis echter dat hetzelfde geldt voor andere belangrijke gegevens, bijvoorbeeld gegevens over de Nederlandse infrastructuur, zowel fysiek (wegen, bruggen/tunnels, openbaar vervoer, waterleiding, energievoorziening, etc.) als digitaal (datakabels, datacentra, etc.). Iedereen moet zich bewust zijn dat deze gegevens niet moeten worden toevertrouwd aan buitenlandse AI toepassingen en/of gebruikt mogen worden voor training van AI-modellen die publiek gebruikt worden. 
Mijn voorstel is dus om het onderwerp cruciale infrastructuur toe te voegen bij Verantwoord Datagebruik.    
## Leg uit waarom dit een goede toevoeging is aan het Algoritmekader
Ook gegevens over infrastructuur zijn cruciaal voor burger en maatschappij, zeker in tijden van oorlogsdreiging, maar eigenlijk altijd.

**Comment by BartdeVisser** [comment]
@webredactie-algoritmekader : Nout pakt deze op en stemt met jou af.
