### ISSUE TITLE
Gebruik van pre-trained modellen/LLM's

### ISSUE THREAD

**Issue by IneVrenkenNationaalArchief** [MinBZK/Algoritmekader#433]
## Beschrijf je suggestie
Omschrijving.
Bij de ontwikkeling van eigen AI toepassingen is het gebruikelijk om pre-trained modellen (LLM's) te gebruiken die gemaakt zijn door externe/commerciële partijen. Dit omdat er te veel geld, rekenkracht en data nodig is om zelf een nieuw LLM te maken.
Ik mis de eisen waaraan zo'n pre-trained (voorgetraind) model moet voldoen. Omdat LLM's getraind zijn op heel veel data, is vaak niet duidelijk of ze 100% voldoen aan privacy- en eigendomsrecht/auteursrecht, dus eisen daarvoor zijn lastig te stellen. Maar een belangrijke eis die je wel kan stellen is volgens mij dat het pre-trained model moet beschikken over goede bronvermelding, dus moet aangeven waar het de oorspronkelijke data in het antwoord vandaan gehaald heeft. Die bronvermelding is namelijk de enige manier waarop zowel de burger, als ook de developer van de nieuwe AI-toepassing mee kan controleren of de LLM de goede antwoorden geeft. 

## Leg uit waarom dit een goede toevoeging is aan het Algoritmekader
In de toekomst zal het integreren van een gedownload pre-trained modellen vaak voorkomen, om ze vervolgens zelf bij te trainen met eigen, al dan niet vertrouwelijke data (fine-tuning).

**Comment by IneVrenkenNationaalArchief** [comment]
Beste Nout,

Blij dat je iets kan met mijn suggestie over het toevoegen van kaders voor pre-trained modellen, want die worden inderdaad steeds relevanter.

Auteursrecht en ander eigendomsrecht (patent/octrooirecht, naburige rechten, databankrecht)
Goed dat de maatregel “Laat aanbieder(s) bewijs leveren dat de door hen ontwikkelde algoritmes geen inbreuk maken op de auteursrechten van derden met de trainingsdata en de output” beschreven is.

Voor smalle AI is de maatregel goed realiseerbaar, maar voor generatieve AI/LLM’s is het waarschijnlijk niet echt realiseerbaar omdat de meeste LLM’s getraind zijn met ongeveer alle data van het internet, dus ook materiaal waarop auteursrechten kunnen gelden. Daarnaast is internationaal vaak ook vaak databankrecht van toepassing. We kunnen als overheid volgens mij niet volhouden dat we eisen dat generatieve AI-applicaties en/of generatieve AI-modellen/LLM’s volledig moeten voldoen het eigendomsrecht, voordat we ze kunnen gebruiken. Want dat zou betekenen dat de applicaties/modellen vaak geen antwoord kunnen geven op onze vragen. Ik stelde recent aan Copilot vragen over de Europese AI-act en hij gaf duidelijk antwoord. Daarna vroeg ik op welke pagina of welk artikel in de verordening het precies stond en toen kreeg ik als antwoord dat hij dat niet mocht beantwoorden vanwege het auteursrecht. Eerder gaf Copilot wel een precies antwoord, maar nu niet meer; bang voor de consequenties. Een LLM kan volgens mij dus eigenlijk alleen goed werken wanneer eigendomsrecht niet al te strikt wordt toegepast.

Bronvermelding
In het auteursrecht/databankrecht kan hergebruik toegestaan worden onder bepaalde voorwaarden en één mogelijke voorwaarde is bronvermelding. Mijn voorstel is echter om bronvermelding, in de zin van verwijzing naar de oorspronkelijke bron, niet alleen te bekijken vanuit auteursrecht, databankrecht of ander eigendomsrecht. Bij het gebruik van generatieve AI/LLM’s is bronvermelding ook intrinsiek van belang, los van eigendomsrecht. Want, in tegenstelling tot een zoekmachine waarbij het zoekresultaat direct de bronnen toont, geven generatieve AI/LLM’s een antwoord vanuit een brein dat getraind is vanuit meerdere bronnen. Vanuit het oogpunt van de burger is het van cruciaal belang dat generatieve AI/LLM deze verwijzingen naar de bron ook toont, omdat daarnaar doorklikken de enige manier is om te kunnen checken of het antwoord klopt (dus bijvoorbeeld hallucineren of manipuleren te ontdekken. Als overheid moeten we denk ik dit burgerbelang benadrukken. Daarnaast is bronvermelding echter ook van bijzonder belang voor het ontwikkelen van AI, omdat het ook voor ontwikkelaars/trainers van modellen de enige manier is om te kunnen checken of het model goed werkt. En datzelfde geldt ook voor ontwikkelaars die pre-trained modellen gebruiken. NB De meeste generatieve AI/LLM’s (ChatGPT, Copilot, Llama, Perplexity, etc.) houden vanaf het begin rekening hiermee: ze onthouden de bron en geven die ook mee in hun antwoorden. Maar bijvoorbeeld Gemini van Google schijnt het niet te doen/kunnen.

Ik vind de zin “Overweeg om een bronvermelding te laten opnemen.” te vrijblijvend. Ik denk dat we moeten vermelden dat een AI-applicatie en een AI-model verplicht aan bronvermelding moeten doen. En dit dus niet onder bovengenoemde maatregel over het auteursrecht, maar als aparte vereiste/maatregel, nieuw, specifiek voor AI.

Andere regelgeving/maatregelen
Ik weet geen andere wetgeving op dit gebied. Naast de hiervoor genoemde regelgeving gelden algemene regels op het gebied van fysieke en digitale veiligheid (o.a. de BIO). Specifiek voor AI-applicaties en AI-modellen denk ik ook aan het rapport van de AIVD (AI-systemen: ontwikkel ze veilig | Publicatie | AIVD<https://www.aivd.nl/publicaties/documenten/publicaties/2023/02/15/ai-systemen-ontwikkel-ze-veilig>), dus regels op het gebied van voorkomen van achterdeurtjes, reverse enginering, logistiek, etc. Omdat AI getraind is met data, gelden vanzelfsprekend daarnaast alle regels die gelden voor data (privacy-gevoelige data, vertrouwelijke data, beperkt openbare data, geheime data) dus cloud-afwegingskader, etc.

Ik hoop dat het algoritmekader wordt uitgebreid met kaders voor het gebruik van pre-trained modellen bij ontwikkelen van AI, en de eis voor generatieve AI/LLM’s applicaties en modellen om te verwijzen naar de oorspronkelijke bron. Vanzelfsprekend ben ik altijd beschikbaar voor verdere vragen.

Met vriendelijke groet,
Ine

Van: Nout van Deijck ***@***.***>
Verzonden: dinsdag 3 december 2024 11:17
Aan: MinBZK/Algoritmekader ***@***.***>
CC: Vrenken-Reijnders, Ine ***@***.***>; Author ***@***.***>
Onderwerp: Re: [MinBZK/Algoritmekader] Gebruik van pre-trained modellen/LLM's (Issue #433)


Hoi Ine,

superveel dank voor je suggestie! Ik denk dat dit zeker steeds relevanter wordt, dus goed dat je hier een check op doet! :)

Ik zie dat we in het Algoritmekader in elk geval al iets hebben staan over bewijs laten leveren door aanbieders over niet schenden van auteursrechten:
https://minbzk.github.io/Algoritmekader/voldoen-aan-wetten-en-regels/maatregelen/2-owp-16-leveren-bewijs-door-aanbieder-niet-schenden-auteursrechten/

Hier staat ook iets in over bronvermelding. Sluit dit aan bij wat jij bedoelt? Of denk je dat we deze bestaande vereiste nog verder moeten aanscherpen?

Zijn er nog andere wetten of regelgeving waarin je denkt dat er vereisten uit af te leiden zijn voor pre-trained modellen? Dan kunnen we kijken of we daar nieuwe vereisten van moeten maken, of nog andere bestaande vereisten moeten aanscherpen.

Nogmaals enorm bedankt voor je review hierop en laat het vooral weten waar we nog aanscherpingen kunnen doen.

**Comment by IneVrenkenNationaalArchief** [comment]
Ter info nog een link naar een discussie over auteursrecht op Pleio van Martha Romkes:
Vragen rondom genAI en auteursrecht · Community of Practice - Overheidsmedewerkers - Algemeen · Generatieve AI (pleio.nl)<https://generatieveai.pleio.nl/groups/view/7584698b-ee4c-4496-b971-69b7b21120c1/community-of-practice-overheidsmedewerkers-algemeen/questions/view/b3167b9d-9c8e-42ed-8258-6b4addf3a14f/vragen-rondom-genai-en-auteursrecht>
Ik weet niet of je toegang hebt tot Pleio, dus hier het belangrijkste onderdeel:
Auteursrecht buiten Europa.
Het merendeel van de grote taalmodellen is getraind in de Verenigde Staten, waar de Fair Use-doctrine van toepassing is. Deze doctrine maakt het onder bepaalde voorwaarden mogelijk om auteursrechtelijk beschermd materiaal te gebruiken zonder toestemming van de rechthebbende. Het gebruik wordt als Fair Use beschouwd als het transformatief is, wat betekent dat het de oorspronkelijke content op een nieuwe, betekenisvolle manier gebruikt, zonder deze simpelweg te reproduceren. Cruciaal is ook dat de gebruiker geen eigendomsrecht claimt op de oorspronkelijke content. Ontwikkelaars van taalmodellen in Amerika stellen vaak dat de output van een model transformatief is, en dat het proces van modeltraining onder Fair Use valt. Dit maakt het legaal om openbare data te gebruiken, zelfs als deze auteursrechtelijk beschermd is.
In Europa liggen de regels echter anders. Het auteursrecht in de Europese Unie kent strengere beperkingen op het hergebruik van beschermd materiaal, vooral wanneer dit gebeurt zonder expliciete toestemming van de rechthebbenden. Onder EU-wetgeving kan scraping van auteursrechtelijk beschermde data zonder toestemming in veel gevallen als inbreuk worden beschouwd.
De aankomende verplichtingen van de AI-act versterken dit contrast. Vanaf augustus 2025 moeten ontwikkelaars transparant zijn over welke data is gebruikt voor de training van AI-modellen. Dit stelt strengere eisen aan de naleving van auteursrechten. Zonder aanpassing aan deze nieuwe vereisten kan het gebruik van in Amerika getrainde modellen in de EU problematisch worden, tenzij deze modellen voldoen aan de strengere Europese normen. Het is nog onduidelijk of oudere modellen retroactief aan deze regels moeten voldoen, maar het risico bestaat dat een groot aantal bestaande modellen vanaf die datum niet langer legaal bruikbaar is in Europa.
Gedogen? Of meebewegen?
Europa hanteert strikte regels rondom auteursrechten, maar is minder streng in de naleving ervan. Een treffend voorbeeld hiervan is het videoplatform YouTube: een groot deel van de content op dit platform hergebruikt beeldfragmenten, geluidsopnames en citaten die strikt genomen niet zonder toestemming mogen worden gebruikt onder de huidige Europese wetgeving. Hoewel dit in de Verenigde Staten wordt beschermd door de Fair Use-doctrine, is er in Europa geen vergelijkbare uitzondering, waardoor deze video’s formeel in strijd zouden zijn met auteursrechten.
Toch wordt deze praktijk grotendeels gedoogd, wat wijst op een discrepantie tussen wetgeving en handhaving. Hetzelfde dreigt te gebeuren met grote taalmodellen. Strenge regels zijn alleen effectief als ze praktisch uitvoerbaar zijn en consistent worden toegepast. Mijn voorstel is daarom om de wet aan te passen aan de realiteit van digitale innovatie. In plaats van een wet die massaal overtreden wordt maar zelden wordt gehandhaafd, zou Europa moeten streven naar een auteursrechtkader dat ruimte biedt voor technologisch en maatschappelijk verantwoord gebruik van data, zonder de belangen van rechthebbenden te schaden.

Het voorbeeld dat ik noemde in mijn eerdere mail geeft aan dat ik het eens ben met Romkes dat de strikte toepassing van Europees auteursrecht voor GenAI waarschijnlijk niet realistisch is. Ik weet niet hoe dat te verwerken in het Algoritmekader.

Vanuit het Nationaal Archief denk ik minder vanuit auteursrecht, omdat veel van onze archieven gemaakt zijn door de overheid en vallen onder het publieke domein. Daarom concentreer ik me vooral op de verplichting te verwijzen naar de bron die gebruikt is om de GenAI te trainen. Deze verplichting is namelijk, los van het belang van eigendom, van cruciaal belang voor de burger (en AI-ontwikkelaar/aanbieder); omdat het de enige manier is om iets te kunnen verifiëren. Dus, ook wanneer auteursrecht of ander eigendomsrecht niet van toepassing is (publiek domein, of historische archieven, etc.), blijft bronvermelding cruciaal. Vandaar mijn pleidooi om dit op te nemen in het Algoritmekaders als aparte maatregel, specifiek voor AI.

Groet,
Ine

Van: Vrenken-Reijnders, Ine
Verzonden: dinsdag 3 december 2024 14:05
Aan: 'MinBZK/Algoritmekader' ***@***.***>; MinBZK/Algoritmekader ***@***.***>
CC: Author ***@***.***>
Onderwerp: RE: [MinBZK/Algoritmekader] Gebruik van pre-trained modellen/LLM's (Issue #433)

Beste Nout,

Blij dat je iets kan met mijn suggestie over het toevoegen van kaders voor pre-trained modellen, want die worden inderdaad steeds relevanter.

Auteursrecht en ander eigendomsrecht (patent/octrooirecht, naburige rechten, databankrecht)
Goed dat de maatregel “Laat aanbieder(s) bewijs leveren dat de door hen ontwikkelde algoritmes geen inbreuk maken op de auteursrechten van derden met de trainingsdata en de output” beschreven is.

Voor smalle AI is de maatregel goed realiseerbaar, maar voor generatieve AI/LLM’s is het waarschijnlijk niet echt realiseerbaar omdat de meeste LLM’s getraind zijn met ongeveer alle data van het internet, dus ook materiaal waarop auteursrechten kunnen gelden. Daarnaast is internationaal vaak ook vaak databankrecht van toepassing. We kunnen als overheid volgens mij niet volhouden dat we eisen dat generatieve AI-applicaties en/of generatieve AI-modellen/LLM’s volledig moeten voldoen het eigendomsrecht, voordat we ze kunnen gebruiken. Want dat zou betekenen dat de applicaties/modellen vaak geen antwoord kunnen geven op onze vragen. Ik stelde recent aan Copilot vragen over de Europese AI-act en hij gaf duidelijk antwoord. Daarna vroeg ik op welke pagina of welk artikel in de verordening het precies stond en toen kreeg ik als antwoord dat hij dat niet mocht beantwoorden vanwege het auteursrecht. Eerder gaf Copilot wel een precies antwoord, maar nu niet meer; bang voor de consequenties. Een LLM kan volgens mij dus eigenlijk alleen goed werken wanneer eigendomsrecht niet al te strikt wordt toegepast.

Bronvermelding
In het auteursrecht/databankrecht kan hergebruik toegestaan worden onder bepaalde voorwaarden en één mogelijke voorwaarde is bronvermelding. Mijn voorstel is echter om bronvermelding, in de zin van verwijzing naar de oorspronkelijke bron, niet alleen te bekijken vanuit auteursrecht, databankrecht of ander eigendomsrecht. Bij het gebruik van generatieve AI/LLM’s is bronvermelding ook intrinsiek van belang, los van eigendomsrecht. Want, in tegenstelling tot een zoekmachine waarbij het zoekresultaat direct de bronnen toont, geven generatieve AI/LLM’s een antwoord vanuit een brein dat getraind is vanuit meerdere bronnen. Vanuit het oogpunt van de burger is het van cruciaal belang dat generatieve AI/LLM deze verwijzingen naar de bron ook toont, omdat daarnaar doorklikken de enige manier is om te kunnen checken of het antwoord klopt (dus bijvoorbeeld hallucineren of manipuleren te ontdekken. Als overheid moeten we denk ik dit burgerbelang benadrukken. Daarnaast is bronvermelding echter ook van bijzonder belang voor het ontwikkelen van AI, omdat het ook voor ontwikkelaars/trainers van modellen de enige manier is om te kunnen checken of het model goed werkt. En datzelfde geldt ook voor ontwikkelaars die pre-trained modellen gebruiken. NB De meeste generatieve AI/LLM’s (ChatGPT, Copilot, Llama, Perplexity, etc.) houden vanaf het begin rekening hiermee: ze onthouden de bron en geven die ook mee in hun antwoorden. Maar bijvoorbeeld Gemini van Google schijnt het niet te doen/kunnen.

Ik vind de zin “Overweeg om een bronvermelding te laten opnemen.” te vrijblijvend. Ik denk dat we moeten vermelden dat een AI-applicatie en een AI-model verplicht aan bronvermelding moeten doen. En dit dus niet onder bovengenoemde maatregel over het auteursrecht, maar als aparte vereiste/maatregel, nieuw, specifiek voor AI.

Andere regelgeving/maatregelen
Ik weet geen andere wetgeving op dit gebied. Naast de hiervoor genoemde regelgeving gelden algemene regels op het gebied van fysieke en digitale veiligheid (o.a. de BIO). Specifiek voor AI-applicaties en AI-modellen denk ik ook aan het rapport van de AIVD (AI-systemen: ontwikkel ze veilig | Publicatie | AIVD<https://www.aivd.nl/publicaties/documenten/publicaties/2023/02/15/ai-systemen-ontwikkel-ze-veilig>), dus regels op het gebied van voorkomen van achterdeurtjes, reverse enginering, logistiek, etc. Omdat AI getraind is met data, gelden vanzelfsprekend daarnaast alle regels die gelden voor data (privacy-gevoelige data, vertrouwelijke data, beperkt openbare data, geheime data) dus cloud-afwegingskader, etc.

Ik hoop dat het algoritmekader wordt uitgebreid met kaders voor het gebruik van pre-trained modellen bij ontwikkelen van AI, en de eis voor generatieve AI/LLM’s applicaties en modellen om te verwijzen naar de oorspronkelijke bron. Vanzelfsprekend ben ik altijd beschikbaar voor verdere vragen.

Met vriendelijke groet,
Ine

Van: Nout van Deijck ***@***.******@***.***>>
Verzonden: dinsdag 3 december 2024 11:17
Aan: MinBZK/Algoritmekader ***@***.******@***.***>>
CC: Vrenken-Reijnders, Ine ***@***.******@***.***>>; Author ***@***.******@***.***>>
Onderwerp: Re: [MinBZK/Algoritmekader] Gebruik van pre-trained modellen/LLM's (Issue #433)


Hoi Ine,

superveel dank voor je suggestie! Ik denk dat dit zeker steeds relevanter wordt, dus goed dat je hier een check op doet! :)

Ik zie dat we in het Algoritmekader in elk geval al iets hebben staan over bewijs laten leveren door aanbieders over niet schenden van auteursrechten:
https://minbzk.github.io/Algoritmekader/voldoen-aan-wetten-en-regels/maatregelen/2-owp-16-leveren-bewijs-door-aanbieder-niet-schenden-auteursrechten/

Hier staat ook iets in over bronvermelding. Sluit dit aan bij wat jij bedoelt? Of denk je dat we deze bestaande vereiste nog verder moeten aanscherpen?

Zijn er nog andere wetten of regelgeving waarin je denkt dat er vereisten uit af te leiden zijn voor pre-trained modellen? Dan kunnen we kijken of we daar nieuwe vereisten van moeten maken, of nog andere bestaande vereisten moeten aanscherpen.

Nogmaals enorm bedankt voor je review hierop en laat het vooral weten waar we nog aanscherpingen kunnen doen.

**Comment by BartdeVisser** [comment]
Hi Ine,

Heel veel dank voor je uitvoerige bijdragen. Erg interessant om te lezen en ik heb een poging gewaagd om je input steviger te verankeren in het Algoritmekader. Gezien de krappe deadline heb ik het voor nu nog even wat 'kaal' gelaten, maar het signaal dat overheden hiermee aan de slag moeten is gegeven. Zie hier een preview van de maatregel: https://minbzk.github.io/Algoritmekader/pr-preview/pr-486/voldoen-aan-wetten-en-regels/maatregelen/2-owp-31-genereren-bronvermelding/?h=bronvermeld. 

Groet en tot donderdag bij de demo?

Bart

**Comment by IneVrenkenNationaalArchief** [comment]
Hi Bart,
Je voorstel ziet er prima uit, dank je wel.
Ik kan donderdag helaas niet bij de demo zijn, maar ga het zeker terugkijken.
Groet, Ine

**Comment by floort** [comment]
De EDPB guidance die vandaag is gepubliceert is oook handig hier: https://www.edpb.europa.eu/system/files/2024-12/edpb_opinion_202428_ai-models_en.pdf

**Comment by BartdeVisser** [comment]
Dank Floor, ik heb een notitie gemaakt bij jouw issue over de EDPB guidance, zodat we deze maatregel daarin meenemen.

**Comment by IneVrenkenNationaalArchief** [comment]
Ik mis in de EDPB guidance de eis tot bronvermelding in het model, dus voor het onthouden van de bron bij het trainen van het AI-model. 
(Het vermelden van de bronnen van de datasets in de technische documentatie is onvoldoende. Het is iets meer werk, maar technisch mogelijk om bij het trainen van een AI-model de precieze bron te onthouden.) 

Onthouden van de bron is noodzakelijk voor:  
o	ontwikkelaars in de ontwikkelfase (testen of het model goed werkt), 
o	burgers in de gebruiksfase (controleren van antwoorden), 
o	toezichthouders/SA’s (controleren rechtmatigheid) 
o	en wellicht ook voor achteraf ‘ontleren’ van persoonsgegevens.
