### ISSUE TITLE
'Bèta' in logo vervangen door 'versie 2.0'

### ISSUE THREAD

**Issue by webredactie-algoritmekader** [MinBZK/Algoritmekader#513]
## Beschrijf je suggestie
@rubenrouwhof: Kun jij vandaag (uiterlijk morgenochtend) het woordje 'Bèta' in logo vervangen door 'versie 2.0'? Oh en kun je dan meteen het woordje 'Het' verwijderen uit het logo? Dus niet 'Het Algoritmekader', maar 'Algoritmekader'. Thnkz!

Dit kan in https://github.com/MinBZK/Algoritmekader/tree/release-v2.0/beta-vervangen-door-2.0

## Leg uit waarom dit een goede toevoeging is aan het Algoritmekader
Vanaf morgen is het namelijk geen betaversie meer, maar een definitieve versie. deze ontwikkelen we wel door, maar dat is bij elke website/app etc. zo.

Dit hebben we net als team besloten in een vergadering.

**Comment by rubenrouwhof** [comment]
Opgelost in https://github.com/MinBZK/Algoritmekader/tree/release-v2.0/beta-vervangen-door-2.0
