### ISSUE TITLE
In visualisatie levenscyclus alle fasen even belangrijk maken

### ISSUE THREAD

**Issue by FrieseWoudloper** [MinBZK/Algoritmekader#53]
In het plaatje van de levenscyclus van een algoritmisch systeem is de probleemanalyse fase donkerblauw. De daaropvolgende fasen worden steeds wat lichter. Dit wekt de indruk alsof die fasen minder belangrijk of minder duidelijk zijn. Maar dat is niet zo. Misschien goed om de visualisatie daarop aan te passen.

**Comment by jaspervanderheide** [comment]
@IlseZandbergen en/of @MarjoleinKortemann, kan dit meegenomen worden in vormgever? Lijkt me een goed punt.
