### ISSUE TITLE
Validatie & Verificatie fase in plaats van Validatie

### ISSUE THREAD

**Issue by FrieseWoudloper** [MinBZK/Algoritmekader#54]
De omschrijving van de Validatie-fase in de levenscyclus van een algoritmisch systeem is nu: 

_Nadat het model is ontwikkeld, wordt het gevalideerd om ervoor te zorgen dat het goed presteert op nieuwe, niet eerder geziene gegevens. Dit omvat het evalueren van de nauwkeurigheid en prestaties van het model. Validatie is een interatief proces dat plaatsvindt op verschillende momenten van de levenscyclus._

Ik vind dit verwarrend.

De omschrijving is toegesneden op een (ML?) model. Voor data scientists is modelvalidatie onderdeel van de ontwikkeling van een machine learning model. In de modelvalidatie fase worden de parameters van een ML model gefinetuned. In de modeltest fase wordt vervolgens het beste ML model geselecteerd op basis van de performance op ongeziene data. Als het gaat om het evalueren van een model zou 'Validatie en Testen' dan misschien beter passen.

Maar zoals gezegd, is validatie en testen _zoals gedefinieerd binnen het data science proces op modelniveau_ volgens mij niet wat hier bedoeld wordt. Ik denk dat het veel meer gaat om verificatie en validatie zoals dat in het algemeen gedefinieerd wordt in de levenscyclus van 'gewone' software:

* Verificatie: Is het algoritmisch systeem gebouwd volgens de specificaties?
* Validation: Is het algorimisch systeem geschikt voor het beoogde gebruik en presteert het goed in de praktijk?

Ik denk dat het hierbij ook veel meer gaat om het beantwoorden van de vragen _op socio-technisch systeemniveau_, en niet op modelniveau zoals bij valideren en testen in de ontwikkelfase.

Mijn concrete voorstel is dan ook om 'Validatie' te hernoemen naar 'Verificatie en validatie' en de omschrijving in lijn met wat ik hierboven heb geschreven aan te passen.

**Comment by OXKuiperBZK** [comment]
Hi Willy, dit vind ik een goede opmerking, de life-cycle modellen waarop de huidige van het algoritmekader is gebaseerd zijn wel erg model-gericht, maar het Algoritmekader kijkt ook veel meer naar het socio-technisch systeemniveau, dus dat moeten we duidelijker meenemen. Ik ga dat in de "validatie" stap vermelden (en voorstellen 'verificatie' ook toe te voegen)

**Comment by BartdeVisser** [comment]
Hi Willy,

Nog veel dank voor je input! Nog een paar aanvullende vragen op je voorstel:
- Verificatie: Denk jij dat het uitvoeren van een intern/externe audit hier onderdeel van kan zijn? Ziet wellicht wat minder op het toetsen of de specificaties zijn toegepast, maar wel of de vereisten zijn nageleefd. 
- Validatie: Denk jij dat het uitvoeren van een Pilot, dus voorafgaand aan Implementatie, hier passend is om bij te benoemen?
